# Exception : จัดการข้อผิดพลาด 
# ( โปรแกรมกำลังทำงาน แล้ว มีข้อผิดพลาดเกิดขึ้นจนทำให้โปรแกรมหยุดทำงาน จึงใช้ exceptionในการจัดการเพื่อให้โปรแกรมทำงานต่อไปได้ )


"""
try :           # ลองรันโปรแกรมว่ารันได้ปกติมั้ยที่ try
     คำสั่งรันโปรแกรมปกติ
execpt :         # ถ้ามีข้อผิดพลาดให้มาที่ except
        คำสั่งที่ทำงานตอนโปรแกรมมีข้อผิดพลาด
    
"""

"""

จัดการ exception หลายเหตุการณ์ มีข้อผิดพลาดหลายกรณี 

ValueError => ค่าผิดพลาด (ป้อนตัวอักษรเข้าไป เมื่อระบุให้ใส่ int)
ZeroDivisionError => หารด้วย 0
TypeError => ชนิดข้อมูลไม่เหมือนกัน เช่น 10 + "A" (int + string : ทำไม่ได้)

** ดูหลายชื่อ error ได้โดยลองรันโปรแกรม แล้วนำชื่อนั้นมาใส่ที่ case ที่ except ( ดักข้อผิดพลาดโดยการลองรันโปรแกรมดูก่อน ) **

except case :

"""

try :
    number1 = float(input("ป้อนตัวเลข 1 :"))
    number2 = float(input("ป้อนตัวเลข 2 :"))
    result = number1/number2
    print(result)

except ValueError:
    print("ป้อนตัวเลขเท่านั้นถึงจะหารได้")

except ZeroDivisionError:
    print("ห้ามหารด้วยเลข 0 นะ")

